-- ######################################################
-- #       DeleteBase.sql - Supprime les tables         #
-- #                                                    #
-- # Par Vincent Commin, Louis Leenart & Alexis Louail  #
-- ######################################################

DROP TABLE AUTHOR CASCADE CONSTRAINTS;
DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP TABLE BORROWER CASCADE CONSTRAINTS;
DROP TABLE BORROWERTYPE CASCADE CONSTRAINTS;
DROP TABLE BORROWERTYPE_DOCUMENTTYPE CASCADE CONSTRAINTS;
DROP TABLE CD CASCADE CONSTRAINTS;
DROP TABLE DOCUMENT CASCADE CONSTRAINTS;
DROP TABLE DOCUMENT_AUTHOR CASCADE CONSTRAINTS;
DROP TABLE DOCUMENT_BORROWER CASCADE CONSTRAINTS;
DROP TABLE DOCUMENT_KEYWORDS CASCADE CONSTRAINTS;
DROP TABLE DOCUMENTTYPE CASCADE CONSTRAINTS;
DROP TABLE DVD CASCADE CONSTRAINTS;
DROP TABLE EDITOR CASCADE CONSTRAINTS;
DROP TABLE KEYWORDS CASCADE CONSTRAINTS;
DROP TABLE VIDEO CASCADE CONSTRAINTS;

COMMIT;