--------------------------------------------------------
--  Fichier créé - jeudi-avril-22-2021   
--------------------------------------------------------
REM INSERTING into PROJET.DOCUMENT_BORROWER
SET DEFINE OFF;
Insert into PROJET.DOCUMENT_BORROWER (DOCUMENTID,BORROWERID,DATESTART,DATERETURN) values ('5','16',to_date('15/11/18','DD/MM/RR'),to_date('15/11/19','DD/MM/RR'));
Insert into PROJET.DOCUMENT_BORROWER (DOCUMENTID,BORROWERID,DATESTART,DATERETURN) values ('7','16',to_date('14/11/18','DD/MM/RR'),null);
Insert into PROJET.DOCUMENT_BORROWER (DOCUMENTID,BORROWERID,DATESTART,DATERETURN) values ('2','16',to_date('16/11/19','DD/MM/RR'),null);
Insert into PROJET.DOCUMENT_BORROWER (DOCUMENTID,BORROWERID,DATESTART,DATERETURN) values ('8','5',to_date('16/04/20','DD/MM/RR'),to_date('17/04/20','DD/MM/RR'));
Insert into PROJET.DOCUMENT_BORROWER (DOCUMENTID,BORROWERID,DATESTART,DATERETURN) values ('6','2',to_date('22/04/19','DD/MM/RR'),to_date('22/04/20','DD/MM/RR'));
Insert into PROJET.DOCUMENT_BORROWER (DOCUMENTID,BORROWERID,DATESTART,DATERETURN) values ('3','1',to_date('18/02/15','DD/MM/RR'),null);
Insert into PROJET.DOCUMENT_BORROWER (DOCUMENTID,BORROWERID,DATESTART,DATERETURN) values ('9','6',to_date('03/07/19','DD/MM/RR'),null);
Insert into PROJET.DOCUMENT_BORROWER (DOCUMENTID,BORROWERID,DATESTART,DATERETURN) values ('7','7',to_date('02/02/22','DD/MM/RR'),null);
